# BUILD STAGE
FROM python:3.11-slim as builder

WORKDIR /usr/src/app

ENV POETRY_VERSION="2.1.3"
ENV POETRY_VENV="/opt/poetry-venv"
ENV PATH="${PATH}:${POETRY_VENV}/bin"

RUN python3 -m venv "$POETRY_VENV" \
	&& "$POETRY_VENV/bin/pip" install -U pip setuptools \
	&& "$POETRY_VENV/bin/pip" install poetry=="${POETRY_VERSION}"

COPY pyproject.toml poetry.lock repeated_calls/basic_mcp_server/README.md  ./
COPY repeated_calls/ repeated_calls

RUN poetry config virtualenvs.in-project true && \
    poetry install --only main && \
    poetry build --format wheel

# RUNTIME STAGE
FROM python:3.11-slim

WORKDIR /usr/src/app

ENV PYTHONUNBUFFERED="1"

COPY --from=builder /usr/src/app/dist/*.whl /usr/src/app/
COPY --from=builder /usr/src/app /usr/src/app

RUN apt-get update && apt-get upgrade -y && apt-get clean && \
    pip install dist/*.whl

RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser
RUN chown -R appuser:appgroup /usr/src/app

USER appuser

EXPOSE 8000

CMD ["uvicorn", "repeated_calls.basic_mcp_server.operations.operations_mcp_server:app", "--host", "0.0.0.0", "--port", "8000"]
