version: 1
disable_existing_loggers: no
formatters:
  simple:
    format: "[%(asctime)s.%(msecs)03d] %(levelname)-8s - %(filename)s - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
  verbose:
    format: "[%(asctime)s.%(msecs)03d] %(levelname)-8s - %(filename)s:%(funcName)s:%(lineno)d - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
  minimal:
    format: "%(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  demo:
    class: logging.StreamHandler
    formatter: minimal
    stream: ext://sys.stdout
    '.':
      terminator: "\n\n===========================\n\n"
loggers:
  root:
    level: WARNING
    handlers:
      - console
  default:
    level: DEBUG
    handlers:
      - console
    propagate: no
